### ISSUE TITLE
Full screen mode.

### ISSUE THREAD

**Issue by andriykrypov** [ajbogh/video-js-html5Thumbnails#2]
Plugin does not want to work correctly in Full Screen player mode.

**Comment by ajbogh** [comment]
Nice catch. I didn't test this feature, which makes me want to write tests for this. It turns out the code only "remembers" the original width of the video, not the new width which is the same as the screen. I have to detect the fullscreen event and change the width calculation to take the full screen into account. 

Keep an eye out for the update in the next few days.

**Comment by ajbogh** [comment]
This is fixed in this commit: 560dd1db428757b825766bea0482d6d139af8caa

**Comment by andriykrypov** [comment]
Perfect work!
Thanks.
